[project]
name = "pyrate"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"



dependencies = []

[tool.uv]
dev-dependencies = [
    "ruff",
    "pytest",
    "black",
    "mypy",
]
